# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.1
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _graph
else:
    import _graph

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _graph.delete_SwigPyIterator

    def value(self):
        return _graph.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _graph.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _graph.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _graph.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _graph.SwigPyIterator_equal(self, x)

    def copy(self):
        return _graph.SwigPyIterator_copy(self)

    def next(self):
        return _graph.SwigPyIterator_next(self)

    def __next__(self):
        return _graph.SwigPyIterator___next__(self)

    def previous(self):
        return _graph.SwigPyIterator_previous(self)

    def advance(self, n):
        return _graph.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _graph.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _graph.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _graph.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _graph.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _graph.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _graph.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _graph:
_graph.SwigPyIterator_swigregister(SwigPyIterator)

class PairIntInt(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _graph.PairIntInt_swiginit(self, _graph.new_PairIntInt(*args))
    first = property(_graph.PairIntInt_first_get, _graph.PairIntInt_first_set)
    second = property(_graph.PairIntInt_second_get, _graph.PairIntInt_second_set)
    def __len__(self):
        return 2
    def __repr__(self):
        return str((self.first, self.second))
    def __getitem__(self, index): 
        if not (index % 2):
            return self.first
        else:
            return self.second
    def __setitem__(self, index, val):
        if not (index % 2):
            self.first = val
        else:
            self.second = val
    __swig_destroy__ = _graph.delete_PairIntInt

# Register PairIntInt in _graph:
_graph.PairIntInt_swigregister(PairIntInt)

class PairDoubleInt(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _graph.PairDoubleInt_swiginit(self, _graph.new_PairDoubleInt(*args))
    first = property(_graph.PairDoubleInt_first_get, _graph.PairDoubleInt_first_set)
    second = property(_graph.PairDoubleInt_second_get, _graph.PairDoubleInt_second_set)
    def __len__(self):
        return 2
    def __repr__(self):
        return str((self.first, self.second))
    def __getitem__(self, index): 
        if not (index % 2):
            return self.first
        else:
            return self.second
    def __setitem__(self, index, val):
        if not (index % 2):
            self.first = val
        else:
            self.second = val
    __swig_destroy__ = _graph.delete_PairDoubleInt

# Register PairDoubleInt in _graph:
_graph.PairDoubleInt_swigregister(PairDoubleInt)

class VecDouble(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _graph.VecDouble_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _graph.VecDouble___nonzero__(self)

    def __bool__(self):
        return _graph.VecDouble___bool__(self)

    def __len__(self):
        return _graph.VecDouble___len__(self)

    def __getslice__(self, i, j):
        return _graph.VecDouble___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _graph.VecDouble___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _graph.VecDouble___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _graph.VecDouble___delitem__(self, *args)

    def __getitem__(self, *args):
        return _graph.VecDouble___getitem__(self, *args)

    def __setitem__(self, *args):
        return _graph.VecDouble___setitem__(self, *args)

    def pop(self):
        return _graph.VecDouble_pop(self)

    def append(self, x):
        return _graph.VecDouble_append(self, x)

    def empty(self):
        return _graph.VecDouble_empty(self)

    def size(self):
        return _graph.VecDouble_size(self)

    def swap(self, v):
        return _graph.VecDouble_swap(self, v)

    def begin(self):
        return _graph.VecDouble_begin(self)

    def end(self):
        return _graph.VecDouble_end(self)

    def rbegin(self):
        return _graph.VecDouble_rbegin(self)

    def rend(self):
        return _graph.VecDouble_rend(self)

    def clear(self):
        return _graph.VecDouble_clear(self)

    def get_allocator(self):
        return _graph.VecDouble_get_allocator(self)

    def pop_back(self):
        return _graph.VecDouble_pop_back(self)

    def erase(self, *args):
        return _graph.VecDouble_erase(self, *args)

    def __init__(self, *args):
        _graph.VecDouble_swiginit(self, _graph.new_VecDouble(*args))

    def push_back(self, x):
        return _graph.VecDouble_push_back(self, x)

    def front(self):
        return _graph.VecDouble_front(self)

    def back(self):
        return _graph.VecDouble_back(self)

    def assign(self, n, x):
        return _graph.VecDouble_assign(self, n, x)

    def resize(self, *args):
        return _graph.VecDouble_resize(self, *args)

    def insert(self, *args):
        return _graph.VecDouble_insert(self, *args)

    def reserve(self, n):
        return _graph.VecDouble_reserve(self, n)

    def capacity(self):
        return _graph.VecDouble_capacity(self)
    __swig_destroy__ = _graph.delete_VecDouble

# Register VecDouble in _graph:
_graph.VecDouble_swigregister(VecDouble)

class VecInt(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _graph.VecInt_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _graph.VecInt___nonzero__(self)

    def __bool__(self):
        return _graph.VecInt___bool__(self)

    def __len__(self):
        return _graph.VecInt___len__(self)

    def __getslice__(self, i, j):
        return _graph.VecInt___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _graph.VecInt___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _graph.VecInt___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _graph.VecInt___delitem__(self, *args)

    def __getitem__(self, *args):
        return _graph.VecInt___getitem__(self, *args)

    def __setitem__(self, *args):
        return _graph.VecInt___setitem__(self, *args)

    def pop(self):
        return _graph.VecInt_pop(self)

    def append(self, x):
        return _graph.VecInt_append(self, x)

    def empty(self):
        return _graph.VecInt_empty(self)

    def size(self):
        return _graph.VecInt_size(self)

    def swap(self, v):
        return _graph.VecInt_swap(self, v)

    def begin(self):
        return _graph.VecInt_begin(self)

    def end(self):
        return _graph.VecInt_end(self)

    def rbegin(self):
        return _graph.VecInt_rbegin(self)

    def rend(self):
        return _graph.VecInt_rend(self)

    def clear(self):
        return _graph.VecInt_clear(self)

    def get_allocator(self):
        return _graph.VecInt_get_allocator(self)

    def pop_back(self):
        return _graph.VecInt_pop_back(self)

    def erase(self, *args):
        return _graph.VecInt_erase(self, *args)

    def __init__(self, *args):
        _graph.VecInt_swiginit(self, _graph.new_VecInt(*args))

    def push_back(self, x):
        return _graph.VecInt_push_back(self, x)

    def front(self):
        return _graph.VecInt_front(self)

    def back(self):
        return _graph.VecInt_back(self)

    def assign(self, n, x):
        return _graph.VecInt_assign(self, n, x)

    def resize(self, *args):
        return _graph.VecInt_resize(self, *args)

    def insert(self, *args):
        return _graph.VecInt_insert(self, *args)

    def reserve(self, n):
        return _graph.VecInt_reserve(self, n)

    def capacity(self):
        return _graph.VecInt_capacity(self)
    __swig_destroy__ = _graph.delete_VecInt

# Register VecInt in _graph:
_graph.VecInt_swigregister(VecInt)



